### ISSUE TITLE
Not able to install on latest HA

### ISSUE THREAD

**Issue by FranciscoTrigo** [wfurphy/creative-button-card-templates#5]
Hi.
I am trying to install on the latest version of HA, I prefer to do the second installation method (to edit my dashboard with UI), but when I go to edit the raw yaml with the contents of cbc.yml I get this error:
`Unable to parse YAML: YAMLException: duplicated mapping key (64:3) 61 | - id: cbc_unavailable 62 | icon: "[[[ return variabl ... 63 | icon: "[[[ return variables.i ... 64 | dynamic_icons: --------^ 65 | template: state_helper 66 | variables:`
A similar error happens when I try the recommended installation method too.
Do you have any tips?

**Comment by wfurphy** [comment]
Hi @FranciscoTrigo,
Are you installing release `0.2.1` and did you have it working previously on a previous version of HA?

**Comment by FranciscoTrigo** [comment]
Hi. Yes, I got 0.2.1. And I just tried it for the first time earlier this week.
I just got it working right now by modifying cbc.yml.
The way it is generated at the moment it creates two "dynamic_icons:" keys, which makes it fail.
I renamed the first one to "dynamic_icons1" and now it seems like its working, as I was able to save the config and start adding some of the new templates cards.
I dont know if yet if this change causes any other problem, though

**Comment by wfurphy** [comment]
@FranciscoTrigo I'm glad you got it working, that fix should be absolutely fine as long as you're able to use the `dynamic_icons` template in your cards. 

If it doesn't work can you please paste in the full yaml under `dynamic_icons1` and `dynamic_icons` and I should be able to provide you a fix.

I've been working on an update for some time now so once I have that ready for release the issue will be resolved.

**Comment by wfurphy** [comment]
@FranciscoTrigo Because I was taking way too long to actually get the v0.3 release ready I did a fix v0.2.2 to resolve this.
